environments:
  ucphhpc:
    environment_variables:
      DOCKERHUB_PASSWORD: '{{SECRET:[dockerhub][password]}}'
      DOCKERHUB_USERNAME: '{{SECRET:[dockerhub][username]}}'
    pipelines:
      - gocd-server
pipelines:
  gocd-server:
    group: ucphpc
    locking: off
    materials:
      gocdserver_git:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/rasmunk/docker-gocd-server-swarm.git
        branch: main
    parameters:
      IMAGE: docker-gocd-server-swarm
      IMAGE_TAG: "${GO_REVISION_GOCDSERVER_GIT}"
      DEFAULT_TAG: latest
    template: docker_image