environments:
  docker_image:
    environments:
      GIT_USER: "{{SECRET:[github][username]}}"
    pipelines:
      - gocd-server-swarm
pipelines:
  gocd-server-swarm:
    group: docker_image
    locking: off
    materials:
      gocd_server_swarm_git:  # this is the name of material
        # says about type of material and url at once
        name: gocd-server-swarm
        git: https://github.com/rasmunk/docker-gocd-server-swarm.git
        branch: main
        destination: gocd-server-swarm
      publish_docker_git:  # this is the name of material
        # says about type of material and url at once
        name: publish-docker-scripts
        git: https://github.com/rasmunk/publish-docker-scripts.git
        branch: main
        username: ${GIT_USER}
        password: "{{SECRET:[github][access_token]}}"
        destination: publish-docker-scripts
    parameters:
      IMAGE: docker-gocd-server-swarm
      ARGS: ''
      COMMIT_TAG: v22.3.0
      DEFAULT_TAG: latest
      SRC_DIRECTORY: gocd-server-swarm
      TEST_DIRECTORY: gocd-server-swarm
      PUSH_DIRECTORY: publish-docker-scripts
    template: docker_image