version: '3.7'

services:
  manager:
    image: ucphhpc/gocd-server-swarm:edge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - godata:/godata:rw
    ports:
      - 8153:8153
    env_file:
      - .env
    user: "${UID}:${GID}"

volumes:
  godata:
