services:
  manager:
    image: ucphhpc/gocd-server-swarm:${TAG}
    build:
      context: ./
      dockerfile: Dockerfile
      # IMPORTANT: pass all ARGs used in Dockerfile here to allow optional override from .env file
      args:
        TAG: ${TAG}
        UID: ${UID}
        GID: ${GID}
        GROUP: ${GROUP}
        PLUGIN_SWARM_MAJOR_VERSION: ${PLUGIN_SWARM_MAJOR_VERSION}
        PLUGIN_SWARM_MINOR_VERSION: ${PLUGIN_SWARM_MINOR_VERSION}
        PLUGIN_SWARM_VERSION: ${PLUGIN_SWARM_MAJOR_VERSION}-${PLUGIN_SWARM_MINOR_VERSION}
        PLUGIN_SWARM_NAME: ${PLUGIN_SWARM_NAME}
        SWARM_JAR_NAME: ${SWARM_JAR_NAME}
        SWARM_SHA256_NAME: ${SWARM_SHA256_NAME}
        PLUGIN_GITHUB_MAJOR_VERSION: ${PLUGIN_GITHUB_MAJOR_VERSION}
        PLUGIN_GITHUB_MINOR_VERSION: ${PLUGIN_GITHUB_MINOR_VERSION}
        PLUGIN_GITHUB_VERSION: ${PLUGIN_GITHUB_MAJOR_VERSION}-${PLUGIN_GITHUB_MINOR_VERSION}
        PLUGIN_GITHUB_NAME: ${PLUGIN_GITHUB_NAME}
        GITHUB_JAR_NAME: ${GITHUB_JAR_NAME}
        GITHUB_SHA256_NAME: ${GITHUB_SHA256_NAME}
        PLUGIN_FILE_SECRET_VERSION: ${PLUGIN_FILE_SECRET_VERSION}
        PLUGIN_FILE_NAME: ${PLUGIN_FILE_NAME}
        FILE_SECRET_JAR_NAME: ${FILE_SECRET_JAR_NAME}
        FILE_SECRET_SHA256_NAME: ${FILE_SECRET_SHA256_NAME}
        GO_DATA_DIR: ${GO_DATA_DIR}
        GO_PLUGINS_BUNDLED_DIR: ${GO_PLUGINS_BUNDLED_DIR}
        GO_PLUGINS_EXTERNAL_DIR: ${GO_PLUGINS_EXTERNAL_DIR}
        GO_SECRET_DIR: ${GO_SECRET_DIR}
    env_file:
      - .env
    user: "${UID}:${GID}"
