version: '3.7'

services:
  manager:
    image: ucphhpc/gocd-server-swarm:edge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - godata_config:/godata/config:rw
      - godata_plugins:/godata/plugins:rw
      - godata_db:/godata/db:rw
      - godata_logs:/godata/logs:rw
    ports:
      - 8153:8153
    env_file:
      - .env
    user: "${UID}:${GID}"

volumes:
  godata_config:
  godata_plugins:
  godata_db:
  godata_logs:
  